sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker
install:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: skip
after_success:
  - mvn clean cobertura:cobertura coveralls:report
  - cd target/
  - ls -a
  - docker build -t hub.tencentyun.com/kkg/springboot-mybatis-demo .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin hub.tencentyun.com
  - docker push hub.tencentyun.com/kkg/springboot-mybatis-demo